// <auto-generated />
using System;
using CreditCardApplication.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CreditCardApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201017215127_SeedDataAdded")]
    partial class SeedDataAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CreditCardApplication.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AnnualIncome")
                        .HasColumnType("money");

                    b.Property<int?>("ApplicationCardResultCardId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FisrtName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicationCardResultCardId");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("CreditCardApplication.Models.Card", b =>
                {
                    b.Property<int>("CardId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("APR")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PromotionalMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("CardId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            CardId = 1,
                            APR = 10m,
                            PromotionalMessage = "If you get a card you will also get a free online banking for an year",
                            Type = 0
                        },
                        new
                        {
                            CardId = 2,
                            APR = 20m,
                            PromotionalMessage = "If you order a credit card you can take part in a lottary for five ski vacations in Zillertal.",
                            Type = 1
                        });
                });

            modelBuilder.Entity("CreditCardApplication.Models.Application", b =>
                {
                    b.HasOne("CreditCardApplication.Models.Card", "ApplicationCardResult")
                        .WithMany()
                        .HasForeignKey("ApplicationCardResultCardId");
                });
#pragma warning restore 612, 618
        }
    }
}
